# Generated by Django 3.0.8 on 2021-05-23 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_format', models.CharField(choices=[('10M', '10 man'), ('5M', '5 man'), ('7M', '7 man'), ('3M', '3 man'), ('XB', 'Xball')], max_length=3)),
                ('division', models.CharField(choices=[('AM', 'Amateur'), ('AMA', 'Amateur A'), ('AMB', 'Amateur B'), ('PRO', 'Professional'), ('NOV', 'Novice'), ('SP', 'Semi-Pro'), ('OP', 'Open'), ('RK', 'Rookie'), ('D1', 'Division 1'), ('D2', 'Division 2'), ('D3', 'Division 3'), ('D4', 'Division 4'), ('D5', 'Division 5'), ('TCT', 'Tactical'), ('UNK', 'Unknown'), ('COL', 'College'), ('YNG', 'Young Guns')], max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('place', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('league', models.CharField(choices=[('NPPL', 'National Professional Paintball League'), ('GWS', 'Great Western Series'), ('UWL', 'Ultimate Woodsball League'), ('PRA', 'Professional Referee Association'), ('MSPA', 'MidSouth Paintball Association'), ('WPF', 'World Paintball Federation'), ('WCCP', 'West Coast Classic Paintball'), ('IAO', 'International Amateur Open'), ('ICPL', 'International Classic Paintball League'), ('CFOA', 'Carolina Field Owners Association'), ('WTS', 'Woodsball Tournament Series'), ('INDY', 'Independent Event')], max_length=50)),
                ('year', models.PositiveSmallIntegerField(default=2021)),
                ('location', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=50)),
                ('virtual_league', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('year', 'league', 'location', 'name'), name='unique tournament'),
        ),
        migrations.AddField(
            model_name='score',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
