# Generated by Django 3.0.8 on 2021-06-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='league',
            field=models.CharField(choices=[('NPPL', 'National Professional Paintball League'), ('GWS', 'Great Western Series'), ('UWL', 'Ultimate Woodsball League'), ('PRA', 'Professional Referee Association'), ('MSPA', 'MidSouth Paintball Association'), ('WPF', 'World Paintball Federation'), ('WCCP', 'West Coast Classic Paintball'), ('IAO', 'International Amateur Open'), ('ICPL', 'International Classic Paintball League'), ('CFOA', 'Carolina Field Owners Association'), ('WTS', 'Woodsball Tournament Series'), ('INDY', 'Independent Event'), ('WWC', 'Woodsball World Cup')], max_length=50),
        ),
    ]
