# Generated by Django 3.0.8 on 2020-08-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20200802_1036'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('year', 'league', 'location'), name='unique tournament'),
        ),
    ]
