# Generated by Django 3.0.8 on 2020-08-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20200802_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
