# Generated by Django 3.0.8 on 2020-08-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20200802_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='tournament',
        ),
    ]
