# Generated by Django 3.0.8 on 2021-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20200803_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021),
        ),
    ]
