# Generated by Django 3.0.8 on 2020-08-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_data', models.DateField(verbose_name='data published')),
                ('league', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('location', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_format', models.CharField(choices=[('10M', '10 man'), ('5M', '5 man'), ('7M', '7 man'), ('3M', '3 man'), ('XB', 'Xball')], max_length=3)),
                ('division', models.CharField(choices=[('AM', 'Amateur'), ('AMA', 'Amateur A'), ('AMB', 'Amateur B'), ('PRO', 'Professional'), ('NOV', 'Novice'), ('SP', 'Semi-Pro'), ('RK', 'Rookie'), ('D1', 'Division 1'), ('D2', 'Division 2'), ('D3', 'Division 3'), ('D4', 'Division 4'), ('D5', 'Division 5')], max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('place', models.PositiveSmallIntegerField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
        ),
    ]
