# Generated by Django 3.0.8 on 2020-08-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20200802_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
