# Generated by Django 3.0.8 on 2020-08-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20200802_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='division',
            field=models.CharField(choices=[('AM', 'Amateur'), ('AMA', 'Amateur A'), ('AMB', 'Amateur B'), ('PRO', 'Professional'), ('NOV', 'Novice'), ('SP', 'Semi-Pro'), ('OP', 'Open'), ('RK', 'Rookie'), ('D1', 'Division 1'), ('D2', 'Division 2'), ('D3', 'Division 3'), ('D4', 'Division 4'), ('D5', 'Division 5'), ('TCT', 'Tactical'), ('UNK', 'Unknown'), ('COL', 'College'), ('YNG', 'Young Guns')], max_length=3),
        ),
    ]
